---
- hosts: all
  tasks:
  - name: Install apache2 Package
    apt: name=apache2 state=present
  - name: Copy ports config files
    copy: src=/data/ports.conf dest=/etc/apache2/ports.conf
  - name: Copy index.html file
    copy: src=/data/index.html dest=/var/www/html
    notify:
    - restart apache
  - name: Start and enable apache service
    service: name=apache2 state=restarted enabled=yes
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted

